const wishs = {
  en: [
    "Wishing you all the happiness and success in the world!",
    "May your day be filled with love, laughter, and joy!",
    "Hoping your dreams come true and your goals are achieved!",
    "Sending positive vibes your way!",
    "May today be the start of something wonderful!",
    "Wishing you a day full of peace, love, and tranquility!",
    "May your life be filled with adventure and excitement!",
    "Wishing you health, happiness, and prosperity!",
    "May your heart be filled with love and kindness!",
    "Sending warm thoughts and good wishes your way!",
    "May all your hard work pay off and your efforts be rewarded!",
    "Wishing you a day full of sunshine and happiness!",
    "May you find joy and contentment in all that you do!",
    "Hoping all your hopes and dreams come true!",
    "Wishing you strength and courage to face any challenge!",
    "May you always find success and happiness in life!",
    "Sending you positive energy and good vibes!",
    "Wishing you all the best on your journey!",
    "May your day be as wonderful as you are!",
    "Wishing you a lifetime of love, joy, and happiness!",
    "May your day be filled with laughter and fun!",
    "Hoping you have a bright and beautiful day!",
    "May your day be as special as you are!",
    "Wishing you a day filled with love and laughter!",
    "May all your wishes come true and your dreams become reality!",
    "Sending you love, light, and positivity!",
    "Wishing you all the success and happiness in the world!",
    "Hoping you have a day full of blessings and good fortune!",
    "May your day be filled with kindness and compassion!",
    "Wishing you peace, love, and happiness today and always!",
    "May you always be surrounded by love and positivity!",
    "Hoping you have a day full of smiles and sunshine!",
    "Wishing you a day full of adventure and excitement!",
    "May your day be filled with good news and positive vibes!",
    "Sending you all the love and good wishes in the world!",
    "Hoping you have a day full of laughter and joy!",
    "May your day be as bright and beautiful as you are!",
    "Wishing you a day full of love and inspiration!",
    "May your day be filled with all the things that bring you happiness!",
    "Hoping you have a day full of peace, love, and harmony!",
    "Wishing you a day full of success and prosperity!",
    "May your day be filled with positive energy and good vibes!",
    "Sending you love, light, and happiness today and always!",
    "Hoping you have a day filled with blessings and good fortune!",
    "Wishing you a day full of kindness and compassion!",
    "May your day be filled with all the things that make you happy!",
    "Hoping you have a day full of adventure and excitement!",
    "Wishing you success, love, and happiness in all that you do!",
    "May your day be filled with joy, laughter, and positivity!",
    "Sending you all my love and good wishes for a wonderful day!",
  ],

  zh: [
    "祝你一切顺利，幸福快乐！",
    "愿你的每一天都充满爱、欢笑和快乐！",
    "祝你梦想成真，万事如意！",
    "给你传递正能量，愿你心情愉悦！",
    "愿今天成为美好的开始！",
    "祝你心静如水，生活美满！",
    "愿你的人生充满冒险和刺激！",
    "祝你健康、幸福和繁荣！",
    "愿你的内心充满爱和善良！",
    "给你送去温暖的问候和美好的祝愿！",
    "愿你的努力得到回报，成果累累！",
    "祝你的人生充满阳光和快乐！",
    "愿你在所做的一切中都找到快乐和满足！",
    "愿你的梦想都成真，心愿都实现！",
    "祝你勇气十足，面对挑战无惧！",
    "愿你生活中时时刻刻都能够找到成功和幸福！",
    "给你送去正能量和美好的祝愿！",
    "祝你在人生的旅途中一路顺风！",
    "愿你的人生充满爱和美好！",
    "祝你一生都幸福、快乐、充满爱！",
    "愿你的一天充满欢笑和快乐！",
    "愿你的人生充满光明和美好！",
    "祝你的每一天都特别美好！",
    "愿你的一天充满爱和欢笑！",
    "愿你的所有愿望都成真，所有梦想都实现！",
    "给你送去爱、光明和正能量！",
    "祝你所有的努力都能获得成功和幸福！",
    "愿你的人生充满成功和幸福！",
    "愿你的一天充满友爱和同情心！",
    "祝你今天和以后都平安、快乐、幸福！",
    "愿你时时刻刻都被爱和正能量所包围！",
    "愿你的一天充满微笑和阳光！",
    "祝你的人生充满美好的意外和惊喜！",
    "愿你的每一个愿望都成真，每一个梦想都实现！",
    "给你送去真诚的祝福和美好的愿望！",
    "祝你所有的努力都得到回报和认可！",
    "愿你的一天充满和谐、平静和美好！",
    "祝你生命之树茁壮成长，人生道路一帆风顺！",
    "愿你在漫长的人生旅途中永远充满勇气和信心！",
    "给你送去真心祝福，祝你心想事成！",
    "祝你一天比一天更加美好和精彩！",
    "愿你的人生充满欢笑、快乐和幸福！",
    "祝你的每一天都充满爱和善意！",
    "愿你的生活中到处都是美丽的花朵和幸福的果实！",
    "祝你的人生充满激情和创造力！",
    "愿你的每一个努力都能够得到肯定和认可！",
    "给你送去美好的祝愿和正能量！",
    "祝你在未来的日子里充满信心和勇气！",
    "愿你的生活充满欢声笑语和温馨！",
    "祝你的人生充满自信、勇气和成就感！",
  ],
};
export default wishs;
